### PR TITLE
Create S_CHANGE_SERVANT_ENERGY.1.def

### PR DESCRIPTION
**Pull request by haroldLuiz**

### CODE REVIEW

**Comment by haroldLuiz** [comment]
The dumps i worked with:

```
S_CHANGE_SERVANT_ENERGY
1400
e697
f9 31 04 00 id-low
00 80 0d 00 id-high
04 00 00 00 Type
5c 00 00 00 Energy
```



```
*   4629157 | <- S_SPAWN_SERVANT 
{
  "__raw": " 
  58 00 
  E8 FE 
  42 00 -> offset name
  F9 31 04 00 -> id 
  00 80 0D 00 -> id
  3B 90 02 48 -> x 
  9D 5C 0D 47  -> y
  00 E0 7A 45 -> z 
  E9 DE -> w
  21 00 00 00 -> unk1
  04 00 00 00 -> type
  70 48 C5 04 -> unk 2
  FF 03 
  B4 00 
  18 01
  F1 61 B8 0F Owner
  00 80 00 00 Owner 
  0B 00 00 00
  3E 00 00 00 Energy
  00 00 00 00 40
  00 73 00 65 00 72 00 76 00 61 00 6E 00 74 00 3A 00 34 00 00 00",
  "id": {
    "low": 274937,
    "high": 884736,
    "unsigned": true
  },
  "x": 133696.921875,
  "y": 36188.61328125,
  "z": 4014,
  "w": 57065,
  "unk1": 33,
  "type": 4,
  "unk2": 80038000,
  "unk3": 1023,
  "unk4": 180,
  "unk5": 280,
  "owner": {
    "low": 263741937,
    "high": 32768,
    "unsigned": true
  },
  "unk6": 11,
  "energy": 62,
  "unk7": 0,
  "name": "@servant:4"
}
```

**Comment by alexrp** [comment]
Please document the values you've seen for the `type` field.

**Comment by haroldLuiz** [comment]
those were the only packets i worked with, after this i made a mod who worked perfectly with this definition, i copied the type definition from S_SPAWN_SERVANT.1.def i dont know any other types, i can rename to unk if you want me to.

**Comment by alexrp** [comment]
Well, if the meaning of the field is not clear, it should be called `unk` or something. I don't really like giving names to fields that suggest their meaning is known when it actually isn't.

**Comment by haroldLuiz** [comment]
Done, just tryed to follow the other packet def

**Pull request merged**
