### PR TITLE
Created Def for the PLAYTIME_EVENT_REWARD packets

### PR DESCRIPTION
**Pull request by haroldLuiz**

### CODE REVIEW

**Comment by soler91** [comment]
S_PLAYTIME_EVENT_REWARD_DATA
needs the array name to be defined.
it also prints
> item:1 amount:120 unk2:1 available:true picked:true
item:1 amount:240 unk2:2 available:true picked:true
item:1 amount:360 unk2:3 available:true picked:true
item:1 amount:480 unk2:4 available:true picked:true
item:1 amount:600 unk2:5 available:true picked:true
item:1 amount:720 unk2:6 available:true picked:true
item:2 amount:30 unk2:1 available:true picked:true
item:2 amount:60 unk2:2 available:true picked:true
item:2 amount:120 unk2:3 available:true picked:true
item:2 amount:180 unk2:4 available:true picked:true
item:2 amount:240 unk2:5 available:true picked:true
item:2 amount:300 unk2:6 available:true picked:true

which i believe then "item" should be roll and "unk2" column
amount doesnt really seem like an amount either so probs should go back to unk?

**Comment by soler91** [comment]
Full definition:

```
array items
- uint32 roll
- uint32 minutes
- uint32 column
- uint32 itemId
- uint16 amount
- byte unk
- int32 unk2 #always 0 ?
- bool available
- bool claimed
```

**Comment by meishuu** [comment]
How do we want to do this?

1. @soler91 submits a new PR for .def version 1.
2. @haroldLuiz updates this PR.
3. @soler91 forks [haroldLuiz/tera-data#patch-1](https://github.com/haroldLuiz/tera-data/tree/patch-1), updates it, and submits it as a new PR. (Your call on the versioning.)

**Comment by meishuu** [comment]
Also, @soler91's suggestion has a different length due to an `int32` being changed to `int16` + `byte`.

And I think `roll` is supposed to be `row`?

**Comment by meishuu** [comment]
Unfortunately this one's been obsoleted by #104.

Thank you for the help, though! Please feel free to contribute again in the future.

**Pull request closed without merging**
