### PR TITLE
Rename : `cid` to `gameId`, `guildEmblemId` to `guildId`, `guildName` to `guild`

### PR DESCRIPTION
**Pull request by seraphinush-gaming**

### CODE REVIEW

**Comment by Mister-Kay** [comment]
For S_GET_USER_LIST, `styleHead` and `styleFace` should probably not get renamed

**Comment by seraphinush-gaming** [comment]
For `S_GET_USER_LIST`, `styleHead` and `styleFace` was renamed for consistency with `S_LOGIN` version 6 and above

**Comment by Mister-Kay** [comment]
No, you're mistaken. I'm saying `styleHead` and `styleFace` should not be renamed to `stylehead` and `styleface`. `S_LOGIN` version 6 and above use `styleHead` and `styleFace`.

**Comment by seraphinush-gaming** [comment]
Oh i forget to capitalize i thought i did hmmmm going to close this

**Pull request closed without merging**
