### PR TITLE
Updated KR opcodes

### PR DESCRIPTION
**Pull request by Shinoyx**
S_REMAIN_PLAY_TIME = 48199
S_LOGIN_ARBITER = 29730
S_USER_EXTERNAL_CHANGE = 21338
S_PARTY_MATCH_LINK = 61983
S_SPAWN_BONFIRE = 43983
S_SPAWN_COLLECTION = 41735
S_DESPAWN_COLLECTION = 41270
C_STORE_BUY_ADD_BASKET = 42197
S_BATTLE_FIELD_ENTRANCE_INFO = 47477
S_DESPAWN_DROPITEM = 24308
S_EXIT = 38590

### CODE REVIEW

**Comment by ayx1995** [comment]
Known issues
- Buff bar not showing

**Comment by Mister-Kay** [comment]
Do buffs disappear without proxy? May be a new, unrelated client glitch.

**Comment by Shinoyx** [comment]
@Mister-Kay Without proxy, the buffs are there. 
For some reason I keep receiving S_ABNORMALITY_END packet upon logging in which doesn't happen to NA server. I'm 99% sure S_ABNORMALITY_END opcode is correct though. Just unsure why server keep sending that packet over after logging in

From KR:
 <- S_ABNORMALITY_BEGIN 28000cbce26d0800008000010000000000000000e0ece605ffffff7f000000000100000000000000
<- S_ABNORMALITY_END 100044ade26d080000800001e0ece605
<- S_ABNORMALITY_BEGIN 28000cbce26d0800008000010000000000000000eaece605ffffff7f000000000100000000000000
<- S_ABNORMALITY_END 100044ade26d080000800001eaece605
<- S_ABNORMALITY_BEGIN 28000cbce26d0800008000010000000000000000f4ece605ffffff7f000000000100000000000000

**Comment by Mister-Kay** [comment]
Sorry, I edited your comment since that data includes your character id. I'll look into it, thanks.

**Comment by Shinoyx** [comment]
Thanks!

**Comment by Mister-Kay** [comment]
Yeah those codes certainly look correct. 
S_ABNORMALITY_END character id and abnormality id matched S_ABNORMALITY_BEGIN.
Only strange features are S_ABNORMALITY_BEGIN gives no source (source = 0) and duration was (2^31 - 1). But I believe these just meant it was a permanent self-buff though.

**Comment by Shinoyx** [comment]
@Mister-Kay Those were 7 days login buff. The issue is its not displaying the icon buff on the bar

**Comment by Shinoyx** [comment]
@Mister-Kay After removing skill prediction, the buff icons does shows with no issue. Any idea?

**Pull request merged**
